clear;close all;clc;
SE=ones(3,3);%结构元
img1_ones=255*ones(339,338);%全1图
img2_zeros=zeros(1294,1247);%全0图
img1=imread('fig1.tif');
img2=imread('fig2.tif');
%腐蚀与膨胀
[imd1,ime1]=Erode_Dilation(img1,SE);
[imd2,ime2]=Erode_Dilation(img2,SE);
%交集、差分和互补
img1_inter=img1_ones&img1;
img1_differ=img1_ones&(~img1);
img1_complete=~img1;
img2_inter=img2_zeros&img2;
img2_differ=img2_zeros&(~img2);
img2_complete=~img2;
%作图
figure(1)
subplot(131);imshow(img1);title('original');
subplot(132);imshow(imd1);title('dilate');
subplot(133);imshow(ime1);title('erode');
figure(2)
subplot(131);imshow(img2);title('original');
subplot(132);imshow(imd2);title('dilate');
subplot(133);imshow(ime2);title('erode');
figure(3)
subplot(131);imshow(img1_inter);title('inter')
subplot(132);imshow(img1_differ);title('differencing')
subplot(133);imshow(img1_complete);title('completment')
figure(4)
subplot(131);imshow(img2_inter);title('inter')
subplot(132);imshow(img2_differ);title('differencing')
subplot(133);imshow(img2_complete);title('completment')